use axum::Extension;
use axum::extract::State;
use axum::http::HeaderMap;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use sqlx::PgPool;

use crate::handler::HandlerError;
use crate::handler::HandlerResult;
use crate::handler::HandlerState;

const IDEMPOTENCY_HEADER_KEY: &str = "Idempotency-Key";
const HIT_TEXT: &str = "CACHE_HIT"; // Cached status code found against key.
const MISS_TEXT: &str = "CACHE_MISS"; // Status code queried by key not found.

pub async fn core(
    Extension(identifier): Extension<String>,
    State(state): State<HandlerState>,
    headers: HeaderMap,
) -> HandlerResult<impl IntoResponse> {
    // Key generated by the client as a unique identifier. Will either be used
    // to query an existing previous transaction or set a new one.
    let key = headers
        .get(IDEMPOTENCY_HEADER_KEY)
        .ok_or(StatusCode::BAD_REQUEST)?
        .to_str()
        .map_err(anyhow::Error::from)?;

    // Check for an existing status code stored by the key. If it's there it'll
    // be used to early-return the exact same response.
    // NOTE: Usually the response payload is also cached & returned.
    if let Some(cached_status) = find_status_by_key(&state.pool, &identifier, key).await? {
        let decoded_status = u16::try_from(cached_status).map_err(anyhow::Error::from)?;
        let status_code = StatusCode::from_u16(decoded_status).map_err(anyhow::Error::from)?;

        tracing::info!("[IDEMPOTENCY] cache hit: {key}");
        return Ok((status_code, HIT_TEXT));
    };

    // At this point, we haven't got the key cached so set a fresh one. Best to
    // perform any read/write operations AFTER this has successfully run.
    insert_status_by_key(&state.pool, &identifier, key).await?;
    tracing::info!("[IDEMPOTENCY] cache miss: {key}");

    Ok((StatusCode::CREATED, MISS_TEXT))
}

async fn find_status_by_key(
    pool: &PgPool,
    identifier: &str,
    key: &str,
) -> HandlerResult<Option<i16>> {
    let statement = format!(
        r#"
        SELECT status
        FROM "{}".idempotency
        WHERE key = $1
        AND NOW() < expires_at
    "#,
        identifier
    );

    sqlx::query_scalar(&statement)
        .bind(key)
        .fetch_optional(pool)
        .await
        .map_err(HandlerError::from)
}

async fn insert_status_by_key(pool: &PgPool, identifier: &str, key: &str) -> HandlerResult<()> {
    // NOTE: Added keys are NOT purged on expiry. The behaviour is mocked by
    // selecting rows where the expiry is in the past.
    let statement = format!(
        r#"
        INSERT INTO "{}".idempotency (key, status, expires_at)
        VALUES ($1, $2, NOW() + MAKE_INTERVAL(SECS => $3))
    "#,
        identifier
    );

    sqlx::query(&statement)
        .bind(key)
        .bind(201)
        .bind(86400) // 1 day (seconds) TTL.
        .execute(pool)
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::handler::TEST_ID_HEADER;

    use super::*;

    use reqwest::Client;
    use reqwest::Response;
    use uuid::Uuid;

    const ENDPOINT: &str = "http://localhost:8080/idempotency";

    async fn setup() -> String {
        let app = HandlerState::new().await.unwrap();
        let identifier = Uuid::new_v4().to_string();

        app.new_unique_test_schema(&identifier).await.unwrap();
        identifier
    }

    async fn make_request(identifier: &str) -> Response {
        Client::new()
            .post(ENDPOINT)
            .header(TEST_ID_HEADER, identifier)
            .header(IDEMPOTENCY_HEADER_KEY, "foo")
            .send()
            .await
            .unwrap()
    }

    #[tokio::test]
    async fn should_400_without_header() {
        let identifier = setup().await;

        let response = Client::new()
            .post(ENDPOINT)
            .header(TEST_ID_HEADER, identifier)
            .send()
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }

    #[tokio::test]
    async fn should_201_miss_on_first_request() {
        let identifier = setup().await;

        let response = make_request(&identifier).await;

        assert_eq!(response.status(), StatusCode::CREATED);
        assert_eq!(response.text().await.unwrap(), MISS_TEXT);
    }

    #[tokio::test]
    async fn should_201_hit_on_repeated_request() {
        let identifier = setup().await;

        make_request(&identifier).await;
        let response = make_request(&identifier).await;

        assert_eq!(response.status(), StatusCode::CREATED);
        assert_eq!(response.text().await.unwrap(), HIT_TEXT);
    }
}
