// Idempotency ensures that repeating a request multiple times has the exact
// same effect as making it once. Checking for a unique key, we can safely
// return cached results.
//
// Generally any response body returned in the initial request should be
// duplicated for any subsequent calls i.e. status codes, body etc.

use anyhow::Context;
use axum::Extension;
use axum::extract::State;
use axum::http::HeaderMap;
use axum::http::StatusCode;
use axum::response::IntoResponse;
use sqlx::PgPool;

use crate::handler::HandlerError;
use crate::handler::HandlerResult;
use crate::handler::HandlerState;

const IDEMPOTENCY_HEADER_KEY: &str = "Idempotency-Key";
// Cached status code found against key.
const HIT_TEXT: &str = "CACHE_HIT";
// Status code queried by key not found.
const MISS_TEXT: &str = "CACHE_MISS";

pub async fn core(
    Extension(identifier): Extension<String>,
    State(state): State<HandlerState>,
    headers: HeaderMap,
) -> HandlerResult<impl IntoResponse> {
    // Key generated by the client as a unique identifier. Will either be used
    // to query an existing previous transaction or set a new one.
    let key = headers
        .get(IDEMPOTENCY_HEADER_KEY)
        .ok_or(StatusCode::BAD_REQUEST)?
        .to_str()
        .map_err(anyhow::Error::from)?;

    // Check for an existing status code stored by the key. If it's there it'll
    // be used to early return the exact same response.
    // NOTE: Usually the response payload is also cached and returned.
    if let Some(cached_status) = find_status_by_key(&state.pool, &identifier, key).await? {
        let decoded_status = u16::try_from(cached_status).map_err(anyhow::Error::from)?;
        let status_code = StatusCode::from_u16(decoded_status).map_err(anyhow::Error::from)?;

        tracing::info!("[IDEMPOTENCY] Cache hit: {key}");
        return Ok((status_code, HIT_TEXT));
    };

    // At this point, we haven't got the key cached so set a fresh one. Best to
    // perform any read or write operations AFTER this has successfully run.
    insert_status_by_key(&state.pool, &identifier, key).await?;
    tracing::info!("[IDEMPOTENCY] Cache miss: {key}");

    Ok((StatusCode::CREATED, MISS_TEXT))
}

async fn find_status_by_key(
    pool: &PgPool,
    identifier: &str,
    key: &str,
) -> HandlerResult<Option<i16>> {
    let statement = format!(
        r#"
        SELECT status
        FROM "{identifier}".idempotency
        WHERE key = $1
        AND NOW() < expires_at;
        "#
    );

    sqlx::query_scalar(&statement)
        .bind(key)
        .fetch_optional(pool)
        .await
        .context("[IDEMPOTENCY] Finding an idempotency record")
        .map_err(HandlerError::from)
}

async fn insert_status_by_key(pool: &PgPool, identifier: &str, key: &str) -> HandlerResult<()> {
    let statement = format!(
        r#"
        INSERT INTO "{identifier}".idempotency (key, status, expires_at)
        VALUES ($1, $2, NOW() + MAKE_INTERVAL(SECS => $3));
        "#
    );

    const STATUS_CODE: i32 = 201;
    // NOTE: Upon expiry, the record remains but isn't queried.
    const EXPIRY_SECS: i32 = 86_400;

    sqlx::query(&statement)
        .bind(key)
        .bind(STATUS_CODE)
        .bind(EXPIRY_SECS)
        .execute(pool)
        .await
        .context("[IDEMPOTENCY] Inserting idempotency record")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::handler::HandlerState;
    use crate::handler::TEST_ID_HEADER_KEY;
    use crate::handler::idempotency::HIT_TEXT;
    use crate::handler::idempotency::IDEMPOTENCY_HEADER_KEY;
    use crate::handler::idempotency::MISS_TEXT;

    use axum::http::StatusCode;
    use reqwest::Client;
    use reqwest::Response;

    const ENDPOINT: &str = "http://localhost:8080/idempotency";

    async fn make_request(identifier: &str) -> Response {
        Client::new()
            .post(ENDPOINT)
            .header(TEST_ID_HEADER_KEY, identifier)
            .header(IDEMPOTENCY_HEADER_KEY, "foo")
            .send()
            .await
            .expect("Sending HTTP request")
    }

    #[tokio::test]
    async fn should_400_without_header() {
        let identifier = HandlerState::setup_for_test().await;

        let response = Client::new()
            .post(ENDPOINT)
            .header(TEST_ID_HEADER_KEY, identifier)
            .send()
            .await
            .expect("Sending HTTP request without a header");

        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }

    #[tokio::test]
    async fn should_201_miss_on_first_request() {
        let identifier = HandlerState::setup_for_test().await;

        let response = make_request(&identifier).await;
        assert_eq!(response.status(), StatusCode::CREATED);

        let body = response.text().await.expect("Parsing fresh response body");
        assert_eq!(body, MISS_TEXT);
    }

    #[tokio::test]
    async fn should_201_hit_on_repeated_request() {
        let identifier = HandlerState::setup_for_test().await;

        make_request(&identifier).await;

        let response = make_request(&identifier).await;
        assert_eq!(response.status(), StatusCode::CREATED);

        let body = response.text().await.expect("Parsing cached response body");
        assert_eq!(body, HIT_TEXT);
    }
}
