services:
    database:
        image: postgres:14-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=playground

    redis:
        image: redis:7-alpine
        ports:
            - 6379:6379

    server:
        depends_on:
            - database
            - redis
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=postgres://admin:password@database:5432/playground
            - REDIS_URL=redis://redis:6379
            # Tests hit an already running container, so any logic outside of
            # test modules needs a custom feature as the test flag isn't set.
            - MODE=testing
        volumes:
            # Mount source files for hot reloading.
            - ./src:/app/src
            - ./migrations:/app/migrations
