BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, email)
SELECT format('User %s', series), format('user-%s@example.test', series)
FROM generate_series(1, 250_000) AS series
ON CONFLICT (email) DO NOTHING;

CREATE TABLE IF NOT EXISTS orders (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id),
    order_number TEXT        NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO orders (user_id, order_number)
SELECT series::BIGINT, format('order-%s', series)
FROM generate_series(1, 250_000) AS series
ON CONFLICT (order_number) DO NOTHING;

COMMIT;
