BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    email      TEXT        NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name, email) VALUES
    ('Alice Anderson', 'alice.anderson@example.test'),
    ('Bob Brown',      'bob.brown@example.test'),
    ('Carol Carter',   'carol.carter@example.test'),
    ('David Davis',    'david.davis@example.test'),
    ('Emma Edwards',   'emma.edwards@example.test'),
    ('Frank Foster',   'frank.foster@example.test'),
    ('Grace Green',    'grace.green@example.test'),
    ('Henry Harris',   'henry.harris@example.test'),
    ('Ivy Irving',     'ivy.irving@example.test'),
    ('Jack Johnson',   'jack.johnson@example.test'),
    ('Kate King',      'kate.king@example.test'),
    ('Liam Lewis',     'liam.lewis@example.test'),
    ('Mia Mitchell',   'mia.mitchell@example.test'),
    ('Noah Nelson',    'noah.nelson@example.test'),
    ('Olivia Owens',   'olivia.owens@example.test'),
    ('Peter Parker',   'peter.parker@example.test'),
    ('Quinn Quinn',    'quinn.quinn@example.test'),
    ('Ruby Roberts',   'ruby.roberts@example.test'),
    ('Sam Smith',      'sam.smith@example.test'),
    ('Tina Turner',    'tina.turner@example.test')
ON CONFLICT (email) DO NOTHING;

COMMIT;
