services:
    server:
        build:
            context: .
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            RUST_LOG: trace,tungstenite=warn,tokio_tungstenite=warn,sqlx=warn,axum::serve=info
            DATABASE_URI: postgres://admin:password@database:5432/playground
        volumes:
            - ./src:/app/src
            - ./Cargo.toml:/app/Cargo.toml

    database:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: playground
        volumes:
            - ./config/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

    loki:
        image: grafana/loki:latest
        command:
            - -config.file=/etc/loki/local-config.yaml
            - -log.level=warn

    grafana:
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        environment:
            GF_LOG_LEVEL: warn
            GF_AUTH_ANONYMOUS_ENABLED: true
            GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
            GF_AUTH_DISABLE_LOGIN_FORM: true
        volumes:
            - ./config/loki.yml:/etc/grafana/provisioning/datasources/loki.yml:ro
        depends_on:
            - loki

    alloy:
        image: grafana/alloy:latest
        command:
            - run
            - /etc/alloy/config.alloy
        volumes:
            - ./config/config.alloy:/etc/alloy/config.alloy:ro
            # NOTE: Socket exposure for reading Docker data/logs.
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - loki
